In [1]:
import numpy as np
import pandas as pd
from sklearn import metrics
from sklearn.cross_validation import train_test_split
from sklearn.metrics import euclidean_distances
import spotipy as spot
from pandas.io.json import json_normalize
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
beer = pd.read_csv('einstock1.csv')

In [6]:
!ls

API_key                einstock1.csv          scrape_shopify.ipynb
Untitled.ipynb         einstock2.csv
boxfox_api_key         explore_einstock.ipynb

In [14]:
beer.head()

,Distributors,OnOff Premises,Retail Accounts,ADDR,CITY,STATE,ZIP9,Item Names,JAN,FEB,...,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC,TOTAL
0,"Wine Warehouse - South, CA",OFF,WHOLE FOODS VEN #10333,225 S LINCOLN BLVD,VENICE,CA,90291,Einstok Icelandic White Ale 4/6 Btl,7.0,8.0,...,13.0,14.0,9.0,11.0,11.0,10.0,41.0,12.0,9.0,155.0
1,"Wine Warehouse - South, CA",OFF,WHOLE FOODS VEN #10333,225 S LINCOLN BLVD,VENICE,CA,90291,Einstok Icelandic Pale Ale 4/6 Btl,1.0,5.0,...,5.0,6.0,2.0,4.0,2.0,5.0,3.0,4.0,5.0,45.0
2,"Wine Warehouse - South, CA",OFF,WHOLE FOODS VEN #10333,225 S LINCOLN BLVD,VENICE,CA,90291,Einstok Icelandic Toasted Porter 4/6 Btl,1.0,2.0,...,1.0,2.0,2.0,4.0,3.0,1.0,2.0,2.0,1.0,22.0
3,"Wine Warehouse - South, CA",OFF,WHOLE FOODS VEN #10333,225 S LINCOLN BLVD,VENICE,CA,90291,Einstok Icelandic Doppelbock 4/6 Btl,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,3.0,4.0
4,"Wine Warehouse - South, CA",OFF,WHOLE FOODS VEN #10333,225 S LINCOLN BLVD,VENICE,CA,90291,Einstok Icelandic Doppelbock 1/4 Keg,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0

In [13]:
beer.groupby('Item Names')[beer.columns[8:-1]].sum()

,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC
Item Names,,,,,,,,,,,,
Einstok Icelandic Arctic Berry Ale 4/6 Can,0.000000,0.000000,0.000000,101.000000,277.000,413.041667,274.000000,98.250000,0.000000,0.000000,0.000000,0.000000
Einstok Icelandic Arctic Berry Ale 50L Keg,0.000000,0.000000,0.000000,6.000000,10.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Einstok Icelandic Doppelbock 1/4 Keg,0.000000,0.000000,0.000000,0.000000,0.000,0.000000,0.000000,0.000000,4.000000,8.000000,12.000000,0.000000
Einstok Icelandic Doppelbock 4/6 Btl,0.000000,0.000000,0.000000,0.000000,0.000,0.000000,0.000000,0.000000,36.750000,342.250000,377.041667,242.083333
Einstok Icelandic Doppelbock 50L Keg,-1.000000,7.000000,7.000000,6.000000,0.000,0.000000,0.000000,3.000000,0.000000,5.000000,3.000000,1.000000
Einstok Icelandic Pale Ale 1/4 Keg,0.000000,6.000000,14.000000,10.000000,10.000,3.000000,7.000000,18.000000,3.000000,5.000000,2.000000,14.000000
Einstok Icelandic Pale Ale 4/6 Btl,501.166667,528.500000,563.000000,606.250000,609.000,718.250000,619.000000,705.041667,631.250000,573.000000,645.250000,771.000000
Einstok Icelandic Pale Ale 50L Keg,0.000000,0.000000,0.000000,0.000000,6.000,6.000000,2.000000,0.000000,5.000000,0.000000,0.000000,17.000000
Einstok Icelandic Toasted Porter 1/4 Keg,0.000000,0.000000,0.000000,3.000000,24.000,22.000000,21.000000,24.000000,22.000000,23.000000,34.000000,29.000000
Einstok Icelandic Toasted Porter 1/6 Keg,18.000000,16.000000,15.000000,16.000000,5.000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Einstok Icelandic Toasted Porter 4/6 Btl,554.250000,556.541667,521.250000,590.458333,549.000,599.041667,542.250000,595.041667,654.041667,599.500000,711.000000,840.000000
Einstok Icelandic White Ale 1/4 Keg,0.000000,0.000000,27.000000,26.000000,68.000,8.000000,38.000000,10.000000,21.000000,22.000000,29.000000,34.000000
Einstok Icelandic White Ale 30L Keg,3.000000,16.000000,5.000000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Einstok Icelandic White Ale 4/6 Btl,1720.583333,2109.583334,2472.083334,2333.041667,2243.125,2978.750000,2465.291667,2704.083334,2643.875001,2281.041667,2497.416667,2484.166667
Einstok Icelandic White Ale 50L Keg,93.000000,115.000000,141.000000,137.000000,39.000,64.000000,92.000000,145.000000,123.000000,138.000000,138.000000,118.000000

In [5]:
beer[beer['OnOff Premises'] == 'ON'].head()

,Distributors,OnOff Premises,Retail Accounts,ADDR,CITY,STATE,ZIP9,Item Names,JAN,FEB,...,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC,TOTAL
2223,"Wine Warehouse - South, CA",ON,PERCH/347314,448 S HILL ST #1312,LOS ANGELES,CA,90013,Einstok Icelandic Toasted Porter 4/6 Btl,14.0,13.0,...,16.0,18.0,21.0,18.0,20.0,26.0,22.0,16.0,14.0,211.0
2224,"Wine Warehouse - South, CA",ON,PERCH/347314,448 S HILL ST #1312,LOS ANGELES,CA,90013,Einstok Icelandic White Ale 4/6 Btl,20.0,32.0,...,39.0,27.0,41.0,0.0,0.0,0.0,0.0,0.0,0.0,185.0
2225,"Wine Warehouse - South, CA",ON,PERCH/347314,448 S HILL ST #1312,LOS ANGELES,CA,90013,Einstok Icelandic White Ale 50L Keg,2.0,5.0,...,5.0,5.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,25.0
2226,"Wine Warehouse - South, CA",ON,PERCH/347314,448 S HILL ST #1312,LOS ANGELES,CA,90013,Einstok Icelandic White Ale 1/4 Keg,0.0,0.0,...,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
2227,"Wine Warehouse - South, CA",ON,BRICKYARD NO HO,11130 MAGNOLIA BD,NORTH HOLLYWOOD,CA,91601,Einstok Icelandic White Ale 4/6 Btl,18.0,19.0,...,18.0,15.0,23.0,17.0,12.0,21.0,13.0,12.0,13.0,203.0

In [27]:
beer['Retail Accounts'].nunique()

2097